name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: aa-demo-org/hello-world-docker-action@v1.0
        with:
          who-to-greet: '@octocat'
